name: adkach
description: AdKach App.

version: 1.0.0+5

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hidden_drawer_menu: ^3.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7

  readmore: ^2.2.0
  google_fonts: ^6.1.0
  fl_chart: ^0.64.0
  circular_countdown_timer: ^0.2.3
  google_mobile_ads: ^3.1.0

  line_awesome_flutter: ^2.0.0

  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.2.0

  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.4
  intl_phone_field: ^3.2.0
  intl: ^0.18.1
  http: ^1.1.0

  sensitive_clipboard: ^1.0.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.0
  simple_barcode_scanner: ^0.0.8
  flutter_launcher_icons: ^0.13.1
  jwt_decoder: ^2.0.1
  unity_ads_plugin: ^0.3.10
  any_animated_button: ^0.0.4
  nice_buttons: ^0.0.3
  url_launcher: ^6.2.4
  flutter_screenutil: ^5.9.0
  stacked_notification_cards: ^0.1.0-dev.5
  flutter_linkify: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "AdKach_mobile/assets/img/logonetv.png"
  image_path_ios: "AdKach_mobile/assets/img/logonetv.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  assets:
    - assets/
    - assets/Icons/
    - assets/img/

  fonts:
    - family: San Francisco Display
      fonts:
        - asset: assets/font/SFNSDisplay-Regular.otf
        - asset: assets/font/SFNSDisplay-Medium.otf
          weight: 500
